Notary client provider + removed CLIENT_DOMAIN const
d3ledger/notary pull request #647
Opened 2019-08-27 15:09 UTC by dolgopolovwork

### Description of the Change
New provider called `NotaryClientProvider`. `CLIENT_DOMAIN` is removed.

2019-08-27 15:11 UTC, Alexey-N-Chernyshov approved these changes

2019-08-28 06:42 UTC, Mingela requested changes
- add '@' to tests accounts
- check k->v pair instead of just key
- transform accountId properly

2019-08-28 08:29 UTC, Mingela approved these changes

2019-08-28 11:32 UTC, Mingela approved these changes

2019-08-28 11:47 UTC, merged